package com.example.jwt.item;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest
@AutoConfigureMockMvc
public class JwtAuthenticationTest {

    @Autowired
    private MockMvc mockMvc;

    // Replace with a real JWT generated by your app (e.g., from /auth/login)
    private final String validJwt = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOlsiVVNFUiJdLCJpYXQiOjE3NjU1NjEwOTUsImV4cCI6MTc2NTU2MTM5NX0.qHceBrZedwXzfXxFVzSNFwoKxwYV9Je-VeSPm9GCw5Q";

    @Test
    void testAccessSecuredEndpointWithValidJwt() throws Exception {
        mockMvc.perform(get("/items")
                        .header("Authorization", validJwt)
                        .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk());
    }

    @Test
    void testAccessSecuredEndpointWithoutJwt() throws Exception {
        mockMvc.perform(get("/items")
                        .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isForbidden()); // or Unauthorized depending on config
    }

    @Test
    void testAccessSecuredEndpointWithInvalidJwt() throws Exception {
        mockMvc.perform(get("/items")
                        .header("Authorization", "Bearer invalid.token.value")
                        .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isUnauthorized());
    }
}
